POST http://localhost:3000/api/v1/login
content-type: application/json
{
    "code": "HTG-1",
    "password": "123"
}
###

# POST http://localhost:3000/api/v1/logout
# content-type: application/json
# Authorization: 'Bearer '
# {
#     "code": "HTG-1",
#     "password": "123"
# }