### Login
POST http://localhost:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
    "code": "STG-1",
    "password": "123"
}

###Logout
POST http://localhost:3000/api/v1/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiSGFtaXMgSGFtaXMiLCJpYXQiOjE3MTEzOTg1OTYsImV4cCI6MTcxMTQwMjE5Nn0.rUAjZHhEulTE5zRuCJ7H5JgpYkpRGH2sEqdnpY_ZCDs

###Register Employee
POST http://localhost:3000/api/v1/employees/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiSGFtaXMgSGFtaXMiLCJpYXQiOjE3MTE0MDI1MTcsImV4cCI6MTcxMTQwNjExN30.EWTVSKVZYVItVm2oe4JzBtZPpvSe-iv_3lhKgWX4zEI

{
    "employer_type_id": 2,
    "country_id": 1,
    "tin": "102-104-289",
    "name": "Management and development for health (MDH)",
    "address": "Plot #802, Mwai Kibaki Road, Mikocheni Dar es Salaam",
    "phone": "255 22 277 1623"
}