POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "codes": "HTG-1",
    "password": "123"
}
###

POST http://localhost:3000/api/v1/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiSGVybWFuIEpvaG5zb24iLCJpYXQiOjE3MTAzNjE5MTAsImV4cCI6MTcxMDM2NTUxMH0.u8TgUxF9eKfYY-CSaa2piNzKv3U94dNArU0SstEF_Ps
